// <auto-generated />
using System;
using Autoszerelo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autoszerelo.Data.Migrations.Munkak
{
    [DbContext(typeof(MunkaDbContext))]
    partial class MunkaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autoszerelo.Model.Munka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allapot")
                        .HasColumnType("int");

                    b.Property<DateTime>("GyartasiEv")
                        .HasColumnType("datetime2");

                    b.Property<string>("HibaLeiras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HibaSulyossag")
                        .HasColumnType("int");

                    b.Property<int>("Kategoria")
                        .HasColumnType("int");

                    b.Property<string>("Rendszam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UgyfelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Munkak");
                });
#pragma warning restore 612, 618
        }
    }
}
