// <auto-generated />
using System;
using Autoszerelo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autoszerelo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autoszerelo.Model.Munka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allapot")
                        .HasColumnType("int");

                    b.Property<DateTime>("GyartasiEv")
                        .HasColumnType("datetime2");

                    b.Property<string>("HibaLeiras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HibaSulyossag")
                        .HasColumnType("int");

                    b.Property<int>("Kategoria")
                        .HasColumnType("int");

                    b.Property<string>("Rendszam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UgyfelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UgyfelId");

                    b.ToTable("Munkak");
                });

            modelBuilder.Entity("Autoszerelo.Model.Ugyfel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ugyfelek");
                });

            modelBuilder.Entity("Autoszerelo.Model.Munka", b =>
                {
                    b.HasOne("Autoszerelo.Model.Ugyfel", "Ugyfel")
                        .WithMany("Munkak")
                        .HasForeignKey("UgyfelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ugyfel");
                });

            modelBuilder.Entity("Autoszerelo.Model.Ugyfel", b =>
                {
                    b.Navigation("Munkak");
                });
#pragma warning restore 612, 618
        }
    }
}
